In [1]:
import numpy as np

In [3]:
global_means = np.load('/datasets/hdf5_data_uv_temp/stats/global_means.npy')
global_means

array([[[[-0.051656  ]],

        [[ 0.16486812]]]], dtype=float32)

In [4]:
global_stds = np.load('/datasets/hdf5_data_uv_temp/stats/global_stds.npy')
global_stds

array([[[[5.5035357]],

        [[4.729792 ]]]], dtype=float32)

In [1]:
import h5py

In [8]:
file = "/datasets/hdf5_data_uv/test/2019.h5"

In [2]:
file = "/datasets/hdf5_data_uv_temp/train/1980.h5"

In [2]:
file = "/datasets/hdf5_data_uvsp_swh_mwp/train/1987.h5"

In [3]:
with h5py.File(file, 'r') as hdf:
	keys = list(hdf.keys())
	print("Keys: %s", keys)
	for key in keys:
		data = hdf[key][:]
		print(f"data for key '{key}' has shape {data.shape}")


Keys: %s ['channel', 'fields', 'latitude', 'longitude', 'time']
data for key 'channel' has shape (5,)
data for key 'fields' has shape (8760, 5, 165, 169)
data for key 'latitude' has shape (165,)
data for key 'longitude' has shape (169,)
data for key 'time' has shape (8760,)


In [10]:
ind = 0
data

array([762624, 762625, 762626, ..., 771381, 771382, 771383], dtype=int32)